apiVersion: v1
kind: Service
metadata:
  name: external
  namespace: kingfisher-system
  labels:
    endpoint-external-ip: enabled
    externalIP: 192.168.10.115-192.168.10.116-192.168.10.117
    externalPort: 80-8080
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: external
